name: OSX
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -e -l {0}
jobs:
  build:
    runs-on: macos-${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.config.name }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - 14
        config:
        - { name: Debug }
        - { name: Release }

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    # For a complete overview of all available pieces of software, see:
    # https://github.com/actions/runner-images/blob/macos-14-arm64/20240402.2/images/macos/macos-14-arm64-Readme.md
    - name: List all the Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"

    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Set conda environment
      uses: mamba-org/setup-micromamba@main
      with:
        environment-name: myenv
        environment-file: environment-dev.yml
        init-shell: bash
        cache-downloads: true

    - name: Configure using CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=${{matrix.config.name}} -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TESTS=ON

    - name: Install
      working-directory: build
      run: cmake --install . --config ${{matrix.config.name}}

    - name: Build
      working-directory: build
      run: cmake --build . --config ${{matrix.config.name}} --target test_sparrow_lib --parallel 8

    - name: Run tests
      working-directory: build
      run: ctest -C ${{matrix.config.name}} --output-on-failure
